name: awsiot
version: 0.1
summary: Automatically register your device with AWS IoT.
description: Automatically registers your device with AWS IoT so you can send data to the cloud. This generates automatically a device, a policy, and certificates so you don't have to.
confinement: strict
grade: stable

apps:
  init:
    command: bin/init.sh
    plugs: [network]
  run:
    command: bin/run.sh
    daemon: simple
    plugs: [network]
parts:
  awscli:
    plugin: python
    python-packages: [awscli]
  awsiotsdk:
    plugin: nodejs
    node-packages: [aws-iot-device-sdk, randomstring, shelljs]
  move:
    plugin: dump
    source: src
    organize:
      policy.json: conf/policy.json
      rootca.pem: conf/rootca.pem
      register.js: bin/register.js
      init.sh: bin/init.sh
      run.sh: bin/run.sh
  mqttawsiot:
    plugin: go
    source: src/mqttawsiot
